/*
 * rcc.h
 *
 *  Created on: 2 Kas 2022
 *      Author: SAMEDBASKİN
 */

#ifndef INC_RCC_H_
#define INC_RCC_H_

#include "stm32f407xx.h"


/*
 *
 * GPIO RCC AHB1ENR  ENABLE
 *
 */
#define RCC_GPIOA_CLK_ENABLE() 	    SET_BIT(RCC->AHB1ENR,RCC_AHB1ENR_GPIOAEN)
#define RCC_GPIOB_CLK_ENABLE()      SET_BIT(RCC->AHB1ENR,RCC_AHB1ENR_GPIOBEN)
#define RCC_GPIOC_CLK_ENABLE()   	SET_BIT(RCC->AHB1ENR,RCC_AHB1ENR_GPIOCEN)
#define RCC_GPIOD_CLK_ENABLE()   	SET_BIT(RCC->AHB1ENR,RCC_AHB1ENR_GPIODEN)

#define RCC_SYSCFG_CLK_ENABLE()   	SET_BIT(RCC->APB2ENR,RCC_APB2ENR_SYSCFGEN)

#define RCC_SPI1_CLK_ENABLE()   	SET_BIT(RCC->APB2ENR,RCC_APB2ENR_SPI1EN)

/*
 *
 * GPIO RCC AHB1ENR  DISABLE
 *
 */

#define RCC_GPIOA_CLK_DISABLE() 	CLEAR_BIT(RCC->AHB1ENR,RCC_AHB1ENR_GPIOAEN )
#define RCC_GPIOB_CLK_DISABLE()     CLEAR_BIT(RCC->AHB1ENR,RCC_AHB1ENR_GPIOBEN)
#define RCC_GPIOC_CLK_DISABLE()    	CLEAR_BIT(RCC->AHB1ENR,RCC_AHB1ENR_GPIOCEN)
#define RCC_GPIOD_CLK_DISABLE()   	CLEAR_BIT(RCC->AHB1ENR,RCC_AHB1ENR_GPIODEN)



#endif /* INC_RCC_H_ */
